[package]
name = "cozo"
version = "0.1.0"
edition = "2021"
description = "A database in development"
authors = ["Ziyang Hu"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
casey = "0.3.3"
uuid = { version = "1.1.2", features = ["v1", "v4", "serde"] }
rand = "0.8.5"
anyhow = "1.0"
lazy_static = "1.4.0"
log = "0.4.16"
env_logger = "0.9.0"
smallvec = { version = "1.8.1", features = ["serde", "write", "union", "const_generics", "const_new"] }
smartstring = { version = "1.0.1", features = ["serde"] }
serde_json = "1.0.81"
serde = { version = "1.0.137" }
serde_derive = "1.0.137"
rmp = "0.8.11"
rmp-serde = "1.1.0"
rmpv = "1.0.0"
base64 = "0.13.0"
chrono = "0.4.19"
ordered-float = { version = "3.0", features = ["serde"] }
itertools = "0.10.3"
cozorocks = { path = "cozorocks" }

#[target.'cfg(not(target_env = "msvc"))'.dependencies]
#tikv-jemallocator = { version = "0.5", features = ["disable_initial_exec_tls"] }

#[profile.release]
#lto = true

[workspace]
members = ["cozorocks", "cozohttp", "cozopy", "cozoplay/src-tauri"]