[workspace]
members = [
    "cozo-core",
    "cozorocks",
    "cozoserver",
    "cozo-lib-c",
    "cozo-lib-java",
    "cozo-lib-wasm",
    "cozo-lib-swift",
    "cozo-lib-python",
    "cozo-lib-nodejs"
]
