[package]
name = "cozo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.0"
pest_derive = "2.0"
ordered-float = "2.10.0"
uuid = { version = "0.8", features = ["v1"] }
rand = "0.8.5"
chrono = "0.4"
anyhow = "1.0"
lazy_static = "1.4.0"
thiserror = "1.0.30"
log = "0.4.16"
env_logger = "0.9.0"
actix-web = "4.0.1"
extsort = "0.4.2"
cozorocks = { path = "cozorocks" }