[package]
name = "cozorocks"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = "1.0.69"
miette = "5.3.0"
librocksdb-sys = { version = "=0.8.0", features = ["static", "jemalloc", "lz4", "zstd", "rtti"] }

[build-dependencies]
cxx-build = "1.0.69"