[package]
name = "cozorocks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#autocxx = "0.21.2"
cxx = "1.0.66"

[build-dependencies]
#autocxx-build = "0.21.2"
cxx-build = "1.0.66"
#miette = { version = "4.3", features = ["fancy"] }