[package]
name = "cozorocks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = "1.0.69"
miette = "5.3.0"

[build-dependencies]
cxx-build = "1.0.69"